general:
    
    debug_level : "DEBUG"

    targets_file : "./targets/targets.json" 

    prng_seed : 0

    # Simulation time in seconds
    simulation_time : 100

    # Message rate in messages per second
    msg_rate : 10
    
    # Packet size in bytes
    min_packet_size : 2
    max_packet_size : 1024

    # Packe size distribution
    # Values: uniform and gaussian
    dist_type : "gaussian"

    # Fraction (of the total number of nodes) that inject traffic
    # Values: [0., 1.]
    emitters_fraction : 0.5

    # Inter-message times
    # Values: uniform and gaussian
    inter_msg_type : "uniform"
    
